-- Baseline schema migration
-- Generated from pg_dump of production database (postgres 18).
--
-- All CREATE TABLE/INDEX statements use IF NOT EXISTS so this is safe to run
-- against an existing production database (each statement is a no-op, and the
-- migration is recorded as applied in pgmigrations).
--
-- NOTE: relaterte_oppslag is intentionally excluded. It is owned by the weekly
-- cron job in app/services/oppslagService.js (generateRelatedWords) which drops
-- and recreates it each Sunday at 04:00.
--
-- NOTE: The dates table is a pre-populated calendar lookup table. After running
-- this migration on a fresh database, populate it manually. Example:
--   INSERT INTO dates ("idDate", fulldate, year, month, day, quarter, week, "dayOfWeek", weekend)
--   SELECT ROW_NUMBER() OVER (ORDER BY d)::int,
--          d::date,
--          EXTRACT(year FROM d)::int,
--          EXTRACT(month FROM d)::int,
--          EXTRACT(day FROM d)::int,
--          EXTRACT(quarter FROM d)::int,
--          EXTRACT(week FROM d)::int,
--          EXTRACT(dow FROM d)::int,
--          CASE WHEN EXTRACT(dow FROM d) IN (0,6) THEN 1 ELSE 0 END
--   FROM generate_series('2020-08-01'::date, '2030-12-31'::date, '1 day') AS t(d);

-- Up Migration

CREATE TABLE IF NOT EXISTS oppslag (
    lemma_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oppslag character varying(100),
    ledd character varying(50),
    boy_tabell character varying(15),
    skjult smallint NOT NULL DEFAULT 0,
    opprettet timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sist_endret timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS brukere (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epost character varying(50) NOT NULL,
    locale character varying(5) NOT NULL DEFAULT 'no',
    brukernavn character varying(50) NOT NULL,
    passord_hash character varying(200) NOT NULL,
    admin smallint NOT NULL DEFAULT 0,
    opprettet timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sist_innlogget timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sist_sett timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    opp_periode smallint NOT NULL DEFAULT 7,
    opp_kommentar_eget smallint NOT NULL DEFAULT 1,
    opp_svar smallint NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX IF NOT EXISTS brukere_epost_idx ON brukere USING btree (epost);

CREATE TABLE IF NOT EXISTS definisjon (
    def_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    prioritet smallint NOT NULL DEFAULT 1,
    definisjon character varying(100) NOT NULL,
    oversatt_av bigint,
    opprettet timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sist_endret timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS definisjon_def_id_idx ON definisjon USING btree (def_id);
CREATE INDEX IF NOT EXISTS definisjon_lemma_id_idx ON definisjon USING btree (lemma_id);

CREATE TABLE IF NOT EXISTS uttale (
    uttale_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id),
    transkripsjon character varying(50) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uttale_lemma_id_transkripsjon_idx ON uttale USING btree (lemma_id, transkripsjon);

CREATE TABLE IF NOT EXISTS alle_boyninger (
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id),
    boyning character varying(50) NOT NULL
);

CREATE INDEX IF NOT EXISTS alle_boyninger_boyning_idx ON alle_boyninger USING btree (boyning);
CREATE INDEX IF NOT EXISTS alle_boyninger_lemma_id_idx ON alle_boyninger USING btree (lemma_id);

CREATE TABLE IF NOT EXISTS subst_boy (
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    pos character varying(20) NOT NULL,
    paradigme character varying(10) NOT NULL,
    boy_skjema character varying(10) NOT NULL,
    ubestemt_entall character varying(50),
    bestemt_entall character varying(50),
    ubestemt_flertall character varying(50),
    bestemt_flertall character varying(50),
    PRIMARY KEY (lemma_id, paradigme)
);

CREATE TABLE IF NOT EXISTS verb_boy (
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    pos character varying(20) NOT NULL,
    paradigme character varying(10) NOT NULL,
    boy_skjema character varying(10) NOT NULL,
    infinitiv character varying(50),
    presens character varying(50),
    preteritum character varying(50),
    presens_perfektum character varying(50),
    imperativ character varying(50),
    perf_part_mf character varying(50),
    perf_part_n character varying(50),
    perf_part_bestemt character varying(50),
    perf_part_flertall character varying(50),
    presens_partisipp character varying(50),
    PRIMARY KEY (lemma_id, paradigme)
);

CREATE TABLE IF NOT EXISTS adj_boy (
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    pos character varying(20) NOT NULL,
    paradigme character varying(10) NOT NULL,
    boy_skjema character varying(10) NOT NULL,
    m_entall character varying(50),
    f_entall character varying(50),
    n_entall character varying(50),
    bestemt_entall character varying(50),
    flertall character varying(50),
    komparativ character varying(50),
    superlativ character varying(50),
    superlativ_bestemt character varying(50),
    PRIMARY KEY (lemma_id, paradigme)
);

CREATE TABLE IF NOT EXISTS adv_boy (
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    pos character varying(20) NOT NULL,
    paradigme character varying(10) NOT NULL,
    boy_skjema character varying(10) NOT NULL,
    positiv character varying(50),
    komparativ character varying(50),
    superlativ character varying(50),
    PRIMARY KEY (lemma_id, paradigme)
);

CREATE TABLE IF NOT EXISTS det_boy (
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    pos character varying(20) NOT NULL,
    paradigme character varying(10) NOT NULL,
    boy_skjema character varying(10) NOT NULL,
    m_entall character varying(50),
    f_entall character varying(50),
    n_entall character varying(50),
    bestemt_entall character varying(50),
    flertall character varying(50),
    PRIMARY KEY (lemma_id, paradigme)
);

CREATE TABLE IF NOT EXISTS pron_boy (
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    pos character varying(20) NOT NULL,
    paradigme character varying(10) NOT NULL,
    boy_skjema character varying(50) NOT NULL,
    subjektsform character varying(50),
    objektsform character varying(50),
    PRIMARY KEY (lemma_id, paradigme)
);

CREATE TABLE IF NOT EXISTS frekvens (
    frekvens_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score integer NOT NULL,
    lemma character varying(100) NOT NULL
);

CREATE INDEX IF NOT EXISTS frekvens_lemma_idx ON frekvens USING btree (lemma);

CREATE TABLE IF NOT EXISTS "ønsker" (
    oppslag character varying(50) NOT NULL,
    tidspunkt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dates (
    "idDate" integer PRIMARY KEY,
    fulldate date NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL,
    day integer NOT NULL,
    quarter integer NOT NULL,
    week integer NOT NULL,
    "dayOfWeek" integer NOT NULL,
    weekend integer NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS dates_fulldate_idx ON dates USING btree (fulldate);
CREATE UNIQUE INDEX IF NOT EXISTS dates_year_month_day_idx ON dates USING btree (year, month, day);

CREATE TABLE IF NOT EXISTS eksempler_no (
    no_id integer PRIMARY KEY,
    no_setning text
);

CREATE TABLE IF NOT EXISTS eksempler_ja (
    ja_id integer PRIMARY KEY,
    ja_setning text
);

CREATE TABLE IF NOT EXISTS eksempler_lenker (
    no_id integer NOT NULL REFERENCES eksempler_no (no_id) ON DELETE CASCADE,
    ja_id integer NOT NULL REFERENCES eksempler_ja (ja_id) ON DELETE CASCADE,
    PRIMARY KEY (no_id, ja_id)
);

CREATE INDEX IF NOT EXISTS eksempler_lenker_ja_id_idx ON eksempler_lenker USING btree (ja_id);

CREATE TABLE IF NOT EXISTS forslag (
    forslag_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id),
    user_id bigint REFERENCES brukere (user_id),
    forslag_definisjon character varying(100) NOT NULL,
    status integer NOT NULL DEFAULT 0,
    opprettet timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    godkjent_avvist timestamp without time zone,
    endret smallint NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS forslag_lemma_id_idx ON forslag USING btree (lemma_id);
CREATE INDEX IF NOT EXISTS forslag_user_id_idx ON forslag USING btree (user_id);

CREATE TABLE IF NOT EXISTS stemmer (
    stemme_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forslag_id integer NOT NULL REFERENCES forslag (forslag_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES brukere (user_id) ON DELETE CASCADE,
    type smallint,
    opprettet timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS stemmer_forslag_id_user_id_idx ON stemmer USING btree (forslag_id, user_id);
CREATE INDEX IF NOT EXISTS stemmer_user_id_idx ON stemmer USING btree (user_id);

CREATE TABLE IF NOT EXISTS forslag_kommentarer (
    forslag_kommentar_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forslag_id integer NOT NULL REFERENCES forslag (forslag_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES brukere (user_id) ON DELETE CASCADE,
    kommentar text NOT NULL,
    opprettet timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS forslag_kommentarer_forslag_id_idx ON forslag_kommentarer USING btree (forslag_id);
CREATE INDEX IF NOT EXISTS forslag_kommentarer_user_id_idx ON forslag_kommentarer USING btree (user_id);

CREATE TABLE IF NOT EXISTS forslag_kommentarer_sett (
    forslag_kommentar_id integer NOT NULL REFERENCES forslag_kommentarer (forslag_kommentar_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES brukere (user_id) ON DELETE CASCADE,
    sett_tidspunkt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (forslag_kommentar_id, user_id)
);

CREATE INDEX IF NOT EXISTS forslag_kommentarer_sett_user_id_forslag_kommentar_id_idx ON forslag_kommentarer_sett USING btree (user_id, forslag_kommentar_id);

CREATE TABLE IF NOT EXISTS oppslag_forslag (
    oppslag_forslag_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oppslag character varying(50) NOT NULL,
    boy_tabell character varying(15),
    ledd character varying(50),
    user_id bigint NOT NULL REFERENCES brukere (user_id),
    status integer NOT NULL DEFAULT 0,
    opprettet timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sist_endret timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS oppslag_forslag_oppslag_boy_tabell_idx ON oppslag_forslag USING btree (oppslag, boy_tabell);
CREATE INDEX IF NOT EXISTS oppslag_forslag_user_id_idx ON oppslag_forslag USING btree (user_id);

CREATE TABLE IF NOT EXISTS oppslag_kommentarer (
    oppslag_kommentar_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES brukere (user_id) ON DELETE CASCADE,
    kommentar text NOT NULL,
    opprettet timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS oppslag_kommentarer_lemma_id_idx ON oppslag_kommentarer USING btree (lemma_id);
CREATE INDEX IF NOT EXISTS oppslag_kommentarer_user_id_idx ON oppslag_kommentarer USING btree (user_id);

CREATE TABLE IF NOT EXISTS veggen_innlegg (
    innlegg_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id integer REFERENCES veggen_innlegg (innlegg_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES brukere (user_id),
    innhold text NOT NULL,
    opprettet timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endret smallint NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS veggen_innlegg_parent_id_idx ON veggen_innlegg USING btree (parent_id);
CREATE INDEX IF NOT EXISTS veggen_innlegg_user_id_idx ON veggen_innlegg USING btree (user_id);

CREATE TABLE IF NOT EXISTS veggen_innlegg_sett (
    innlegg_id integer NOT NULL REFERENCES veggen_innlegg (innlegg_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES brukere (user_id) ON DELETE CASCADE,
    sett_tidspunkt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (innlegg_id, user_id)
);

CREATE INDEX IF NOT EXISTS veggen_innlegg_sett_user_id_innlegg_id_idx ON veggen_innlegg_sett USING btree (user_id, innlegg_id);

CREATE TABLE IF NOT EXISTS feedback (
    lemma_id integer NOT NULL REFERENCES oppslag (lemma_id),
    feedback text NOT NULL,
    tidspunkt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS feedback_lemma_id_idx ON feedback USING btree (lemma_id);

CREATE TABLE IF NOT EXISTS page_traffic (
    visit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS oppslag_lemma_id_idx ON oppslag USING btree (lemma_id);
CREATE INDEX IF NOT EXISTS oppslag_oppslag_idx ON oppslag USING btree (oppslag);

-- Down Migration

-- Dropping all tables in reverse dependency order. WARNING: destroys all data.
DROP TABLE IF EXISTS page_traffic;
DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS veggen_innlegg_sett;
DROP TABLE IF EXISTS veggen_innlegg;
DROP TABLE IF EXISTS oppslag_kommentarer;
DROP TABLE IF EXISTS oppslag_forslag;
DROP TABLE IF EXISTS forslag_kommentarer_sett;
DROP TABLE IF EXISTS forslag_kommentarer;
DROP TABLE IF EXISTS stemmer;
DROP TABLE IF EXISTS forslag;
DROP TABLE IF EXISTS eksempler_lenker;
DROP TABLE IF EXISTS eksempler_ja;
DROP TABLE IF EXISTS eksempler_no;
DROP TABLE IF EXISTS dates;
DROP TABLE IF EXISTS "ønsker";
DROP TABLE IF EXISTS frekvens;
DROP TABLE IF EXISTS pron_boy;
DROP TABLE IF EXISTS det_boy;
DROP TABLE IF EXISTS adv_boy;
DROP TABLE IF EXISTS adj_boy;
DROP TABLE IF EXISTS verb_boy;
DROP TABLE IF EXISTS subst_boy;
DROP TABLE IF EXISTS alle_boyninger;
DROP TABLE IF EXISTS uttale;
DROP TABLE IF EXISTS definisjon;
DROP TABLE IF EXISTS brukere;
DROP TABLE IF EXISTS oppslag;
